
import { Experiencia } from "./experienciaLaboral";

export const EXPERIENCIA: Experiencia[] = [
    {id:1,fechaInicio:"Junio 2020", fechaFin:"Actualidad",empresa:"Lafarmen", posicion:"Analista de Marketing", funciones: "Marketing DigitalMarketing Digital Argentina Gestión e implementación de canal directo on-line. Planificación de estrategia digital, tanto de publicidad como logística para e-commerce. Gestión de la comunidad, asesoramiento y atención de cliente final. Desarrollo de productos.Gestión e implementación de canal directo on-line. Planificación de estrategia digital, tanto de publicidad como logística para e-commerce. Gestión de la comunidad, asesoramiento y atención de cliente final. Desarrollo de productos. Estrategia de marketing · Gestión de proyectos · Marketing en Facebook · Marketing digital · Análisis de marketing digital · Capacidad de análisis Aptitudes: Estrategia de marketing · Gestión de proyectos · Marketing en Facebook · Marketing digital · Análisis de marketing digital · Capacidad de análisis Especialista en marketing"},
    {id:2, fechaInicio:"Diciembre 2021", fechaFin:"Actualidad", empresa:"CICUNC", posicion:"Analista de datos", funciones: "Análisis de performance del sitio y sus productos digitales tanto en Google Analytics como en Facebook Meta, con la finalidad de encontrar insights y proponer cursos de acción. Desarrollo de propuestas de mejora y monitoreo de campañas.Análisis de performance del sitio y sus productos digitales tanto en Google Analytics como en Facebook Meta, con la finalidad de encontrar insights y proponer cursos de acción. Desarrollo de propuestas de mejora y monitoreo de campañas. Aptitudes: Estrategia de marketing · Gestión de proyectos · Marketing en Facebook · Google Ads · Marketing digital · Análisis de marketing digital · Capacidad de análisis."},
    {id:3, empresa:"Freelance", posicion:"Marketing Digital" , fechaInicio:"Septiembre 2019",fechaFin:"Junio 2020",funciones:"Publicidad: Facebook Ads y AdWords, Community Managment: Facebook, Messenger Chatbot, Creacion de Contenido : Placas de productos, Desarrollo Web: Construccion de sitios web interactivos. WordPress, Javascript, CSS, HTML, SEO."},
    {id:4, empresa:"Lafarmen S.A", fechaInicio:"Noviembre 2016",fechaFin:" Agosto 2019", posicion: "Analista de Marketing", funciones:"Pronóstico de ventas, análisis de rotación y estacionalidad de los productos. Búsqueda de insights para la propuesta de nuevos productos. Clasificación y análisis de la cartera de clientes. Preparación y presentación de stand institucional. Informatización de procesos para gestión de control."},
    {id:5, empresa:"Lafarmen S.A", fechaInicio:"Enero 2015",fechaFin:" Octubre 2016", posicion: "Analista de Producto", funciones:"Establecer políticas para diagramar volúmenes de producción en base a pronósticos de ventas, y definir las necesidades de materias primas, evitando inmovilizar capital. Evaluar circuitos productivos para determinar si puede reducirse el tiempo de los mismos. Desarrollo de productos y presentación legal. Programación de la producción en función del pronóstico de ventas. Análisis de compras con orientación a justo a tiempo."},
    {id:6, empresa:"Lafarmen S.A", fechaInicio:"Diciembre 2012",fechaFin:" Diciembre 2014", posicion: "Responsable de Sistemas", funciones:"Mantener en funcionamiento la red local de la empresa, Administrar un servidor para clientes remotos en sucursales en Mendoza y Buenos Aires. Monitorear el correcto funcionamiento del sistema operativo base de nuestro servidor en sistema ubuntu. Servicio técnico interno."}
    
]
