
import { Experiencia } from "./experienciaLaboral";

export const EXPERIENCIA: Experiencia[] = [
    {id:0,fechaInicio:"Agosto 2023", fechaFin:"Actualidad",empresa:"Dicsys", posicion:"Digital Data Analyst", funciones: "Implementar un sistema de medicion de activos digitales con Google Analytics, para clientes internos. Esto requiere reunirse con los equipos solicitantes, identificar la necesidad del equipo, generar documentación e implementar eventos personalizados.  Adicionalmente brindo asesoramiento para la explotación de los datos para los solicitantes como para el equipo de desarrollo para implementar el código en el activo/aplicación. ", capacidades:"Google Analytics 4, Javascript, Angular, CSS, Flutter, Dart, GCP, Bigquery, Comunicación, Resolución de conflictos"
    },
    {id:1,fechaInicio:"Junio 2020", fechaFin:"Diciembre 2023",empresa:"Lafarmen", posicion:"Analista de Marketing", funciones: "Marketing Digital Argentina Gestión e implementación de canal directo on-line. Planificación de estrategia digital, tanto de publicidad como logística para e-commerce. Gestión de la comunidad, asesoramiento y atención de cliente final. Desarrollo de productos.Gestión e implementación de canal directo on-line. Capacidad de análisis Especialista en marketing",
      capacidades:"Comunicación, Marketing Digital, Resolución de conflictos, E-commerce: Mercadolibre, Meta, Excel, Goofle Ads"},
    {id:2, fechaInicio:"Diciembre 2021", fechaFin:"Actualidad", empresa:"CICUNC", posicion:"Analista de datos", funciones: "Análisis de performance del sitio y sus productos digitales tanto en Google Analytics como en Facebook Meta, Búsqueda de insights. Desarrollo de propuestas de mejora y monitoreo de campañas. Presentación de reportes en Data Studio", capacidades:"Google Analytics, Javascript, Análisis de datos, Looker, Google Tag Manager, Python, Comunicación, Resolución de conflictos"},
    {id:3, empresa:"Freelance", posicion:"Marketing Digital" , fechaInicio:"Septiembre 2019",fechaFin:"Junio 2020",funciones:"Publicidad: Facebook Ads y AdWords, Community Managment: Facebook, Messenger Chatbot, Creacion de Contenido : Placas de productos, Desarrollo Web: Construccion de sitios web interactivos. WordPress, Javascript, CSS, HTML, SEO.", capacidades:"Meta, Adwords, Content Creation, Wordpress, Javascript, Angular, CSS"},
    {id:4, empresa:"Lafarmen S.A", fechaInicio:"Noviembre 2016",fechaFin:" Agosto 2019", posicion: "Analista de Marketing", funciones:"Pronóstico de ventas, análisis de rotación y estacionalidad de los productos. Búsqueda de insights para la propuesta de nuevos productos. Clasificación y análisis de la cartera de clientes. Preparación y presentación de stand institucional. Informatización de procesos para gestión de control.",
      capacidades:"Google Analytics 4, Javascript, Angular, CSS, Flutter, Dart, GCP, Bigquery, Comunicación, Resolución de conflictos"},
    {id:5, empresa:"Lafarmen S.A", fechaInicio:"Enero 2015",fechaFin:" Octubre 2016", posicion: "Analista de Producto", funciones:"Diagramar y programar volúmenes de producción sobre la base de pronósticos de ventas, definir las necesidades de materias primas. Evaluar y mejorar tiempos de circuitos productivos. Desarrollo de productos y presentaciones legales. Análisis de costos de reposición.", capacidades:"Google Analytics 4, Javascript, Angular, CSS, Flutter, Dart, GCP, Bigquery, Comunicación, Resolución de conflictos"},
    {id:6, empresa:"Lafarmen S.A", fechaInicio:"Diciembre 2012",fechaFin:" Diciembre 2014", posicion: "Responsable de Sistemas", funciones:"Mantener en funcionamiento la red local de la empresa, Administrar un servidor para clientes remotos en sucursales en Mendoza y Buenos Aires. Monitorear el correcto funcionamiento del sistema operativo base de nuestro servidor en sistema ubuntu. Servicio técnico interno.", capacidades:"Google Analytics 4, Javascript, Angular, CSS, Flutter, Dart, GCP, Bigquery, Comunicación, Resolución de conflictos"}
]
